package com.map.invest.mapInvest.util.validacao;

public enum CodigoValidacao implements Codigo {

    // @formatter:off
    ERRO_VALIDACAO("erro.validacao.generico"),
    ERRO_VALIDACAO_CERTIFICADO_OBRIGATORIO("erro.validacao.certificado.obrigatorio"),
    ERRO_VALIDACAO_DADOS_CONTA_INCOMPLETOS("erro.validacao.dados.conta.incompleto"),
    ERRO_VALIDACAO_PAGINA_INVALIDA("erro.validacao.pagina.invalida"),
    ERRO_VALIDACAO_TELA_NAO_CADASTRADA("erro.validacao.tela.invalida"),
    ERRO_VALIDACAO_ENTIDADE_NAO_ENCONTRADA("erro.validacao.entidade.nao.encontrada"),
    ERRO_VALIDACAO_OBRIGATORIO_AO_MENOS_UM_FILTRO("erro.validacao.obrigatorio.ao.menos.um.filtro"),

    ERRO_VALIDACAO_CERTIFICADO_NAO_ENCONTRADO("erro.validacao.certificado.nao.encontrado"),
    ERRO_VALIDACAO_ESTORNO_TIPO_NAO_ENCONTRADO("erro.validacao.estorno.tipo.nao.encontrado"),
    ERRO_VALIDACAO_STATUS_NAO_ENCONTRADO("erro.validacao.status.nao.encontrado"),
    ERRO_STATUS_INVALIDO("erro.certificado.com.status.invalido.para.operacao"),
    ERRO_TIPO_CERTIFICADO_INVALIDO("erro.certificado.com.tipo.certificado.invalido.para.operacao"),

    ERRO_CERTIFICADO_INVALIDO_SEM_SALDO("erro.certificado.com.saldo.invalido.para.operacao"),

    ERRO_VALIDACAO_ESTORNO_MOTIVO_NAO_ENCONTRADO("erro.validacao.estorno.motivo.nao.encontrado"),
    ERRO_VALIDACAO_PORTABILIDADE_NAO_ENCONTRADA("erro.validacao.portabilidade.nao.encontrada"),
    ERRO_VALIDACAO_OBRIGATORIO_INFORMAR_PAGINACAO("erro.validacao.obrigatorio.paginar"),
    ERRO_VALIDACAO_PESSOA_OBRIGATORIA("erro.validacao.pessoa.obrigatoria"),
    ERRO_VALIDACAO_CARTAO_NUMERO("erro.validacao.cartao.numero.errado"),
    ERRO_VALIDACAO_CARTAO_EXTERNO("erro.validacao.cartao.numero.externo.errado"),
    ERRO_DATA_INICIAL_OBRIGATORIO("erro.validacao.data.inicial.obrigatorio"),
    ERRO_DATA_FINAL_OBRIGATORIO("erro.validacao.data.final.obrigatorio"),
    ERRO_DATA_INICIAL_MAIOR_DATA_FINAL("erro.validacao.data.inicial.maior.data.final"),
    ERRO_CPF_INVALIDO("erro.validacao.cpf.invalido"),
    ERRO_CPF_OBRIGATORIO("erro.validacao.cpf.obrigatorio"),
    ERRO_CNPJ_INVALIDO("erro.validacao.cnpj.invalido"),
    ERRO_CNPJ_OBRIGATORIO("erro.validacao.cnpj.obrigatorio"),
    ERRO_PESSOA_NAO_ENCONTRADA("erro.pessoa.nao.encontrada"),
    ERRO_BANCO_AGENCIA_INVALIDO("erro.banco.agencia.invalida"),
    ERRO_EMAIL_OBRIGATORIO("erro.email.obrigatorio"),
    ERRO_EMAIL_INVALIDO("erro.email.invalido"),
    ERRO_COD_CONTA_OBRIGATORIO("erro.codigo.conta.obrigatorio"),

    ERRO_FUNDO_CODIGO_OBRIGATORIO("erro.fundo.codigo.obrigatorio"),
    ERRO_FUNDO_DESCRICAO_OBRIGATORIA("erro.fundo.descricao.obrigatoria"),
    ERRO_FUNDO_INI_VIGENCIA_OBRIGATORIO("erro.fundo.inicio.vigencia.obrigatorio"),
    ERRO_FUNDO_PCT_DESVIO_OBRIGATORIO("erro.fundo.porcentagem.desvio.obrigatorio"),
    ERRO_FUNDO_DIAS_FLOAT_OBRIGATORIO("erro.fundo.dias.float.obrigatorio"),
    ERRO_FUNDO_DIAS_FLOAT_ADM_OBRIGATORIO("erro.fundo.dias.float.adm.obrigatorio"),
    ERRO_FUNDO_DIAS_FLOAT_ADM_INVALIDO("erro.fundo.dias.float.adm.invalido"),
    ERRO_FUNDO_DIAS_FLOAT_UTEIS_MISTO("erro.fundo.dias.float.uteis.misto"),
    ERRO_FUNDO_FLOAT_DIAS_UTEIS_ACRESCIDOS("erro.fundo.dias.uteis.acrescidos"),
    ERRO_PERFIL_INVESTIMENTO_NAO_ENCONTRADO("erro.perfil.investimento.nao.encontrado"),
    ERRO_INDICE_NAO_ENCONTRADO("erro.indice.nao.encontrado"),
    ERRO_OPERACAO_NAO_ENCONTRADA("erro.operacao.nao.encontrada"),
    ERRO_FORMULA_NAO_ENCONTRADA("erro.formula.nao.encontrada"),
    ERRO_FUNDO_EXISTENTE("erro.fundo.existente"),
    ERRO_TAXA_DATA_OBRIGATORIA("erro.taxa.data.obrigatoria"),
    ERRO_TAXA_PCT_TAXA_OBRIGATORIA("erro.taxa.pct.taxa.obrigatoria"),
    ERRO_FUNDO_NAO_ENCONTRADO("erro.fundo.nao.encontrado"),
    ERRO_TAXA_NAO_REMOVIDA("erro.taxa.nao.removida"),
    ERRO_TIPO_FUNDO_INVALIDO("erro.tipo.fundo.invalido"),
    ERRO_FUNDO_CNPJ_INVALIDO("erro.fundo.cnpj.invalido"),
    ERRO_COD_FUNDO_OBRIGATORIO("erro.cod.fundo.obrigatorio"),
    ERRO_VALOR_COTA_OBRIGATORIO("erro.valor.cota.obrigatorio"),
    ERRO_DATA_VALOR_OBRIGATORIO("erro.data.valor.obrigatorio"),
    ERRO_REGISTRO_JA_EXISTENTE("erro.registro.ja.existente"),
    ERRO_NOVO_VALOR_OBRIGATORIO("erro.novo.valor.obrigatorio"),
    ERRO_MOTIVO_ALTERACAO_OBRIGATORIO("erro.motivo.alteracao.obrigatorio"),
    ERRO_NOVO_VALOR_MAIOR_QUE_ZERO("erro.novo.valor.maior.que.zero"),
    ERRO_VALOR_NAO_EXISTENTE_PARA_DATA_INFORMADA("erro.valor.nao.existente.para.data.informada"),
    ERRO_VALOR_NAO_ALTERAVEL("erro.valor.nao.alteravel"),
    ERRO_VALOR_REMOCAO_HISTORICO("erro.valor.remocao.historico"),
    ERRO_VALOR_EMPRESA_NAO_PODE_RECOTIZAR("erro.valor.empresa.nao.pode.recotizar"),
    ERRO_AGENCIA_NAO_ENCONTRADA("erro.agencia.nao.encontrada"),

    ERRO_AGENCIA_COD_AGENCIA_OBRIGATORIO("erro.agencia.cod.agencia.obrigatorio"),
    ERRO_AGENCIA_COD_ENTIDADE_OBRIGATORIO("erro.agencia.cod.entidade.obrigatorio"),
    ERRO_AGENCIA_DESCRICAO_OBRIGATORIA("erro.agencia.descricao.obrigatoria"),
    ERRO_AGENCIA_ESTADO_OBRIGATORIO("erro.agencia.estado.obrigatorio"),
    ERRO_AGENCIA_CIDADE_OBRIGATORIA("erro.agencia.cidade.obrigatoria"),
    ERRO_AGENCIA_ESTADO_INVALIDO("erro.agencia.estado.invalido"),
    ERRO_AGENCIA_CIDADE_INVALIDA("erro.agencia.cidade.invalida"),
    ERRO_AGENCIA_JA_EXISTENTE("erro.agencia.ja.existente"),
    ERRO_AGENCIA_SOMENTE_UM_PADRAO("erro.agencia.somente.um.padrao"),
    ERRO_AGENCIA_GERENTE_INEXISTENTE("erro.agencia.gerente.inexistente"),

    ERRO_ENTIDADE_NAO_ENCONTRADA("erro.entidade.nao.encontrada"),
    ERRO_ENTIDADE_NAO_PODE_SER_NULA("erro.entidade.nao.pode.ser.nula"),
    ERRO_ENTIDADE_COD_ENTIDADE_OBRIGATORIO("erro.entidade.cod.entidade.obrigatorio"),
    ERRO_ENTIDADE_COD_TIPO_ENTIDADE_OBRIGATORIO("erro.entidade.cod.tipo.entidade.obrigatorio"),
    ERRO_ENTIDADE_PESSOA_NAO_INFORMADA("erro.entidade.pessoa.nao.informada"),
    ERRO_ENTIDADE_PESSOA_NAO_ENCONTRADA("erro.entidade.pessoa.nao.encontrada"),
    ERRO_ENTIDADE_SOMENTE_PESSOA_JURIDICA("erro.entidade.somente.pessoa.juridica"),
    ERRO_ENTIDADE_TIPO_INEXISTENTE("erro.entidade.tipo.inexistente"),
    ERRO_ENTIDADE_COD_EXTERNO_OBRIGATORIO_PARA_SEGURADORA("erro.entidade.cod.externo.obrigatorio.para.seguradora"),
    ERRO_ENTIDADE_SERVICO_DUPLICADO("erro.entidade.servico.duplicado"),
    ERRO_ENTIDADE_SERVICO_INEXISTENTE("erro.entidade.servico.inexistente"),
    ERRO_AGENCIA_NAO_PODE_SER_NULA("erro.agencia.nao.pode.ser.nula"),
    ERRO_AGENCIA_GERENTE_PESSOA_FISICA("erro.agencia.gerente.pessoa.fisica"),
    ERRO_ENTIDADE_DUPLICADA("erro.entidade.duplicada"),
    ERRO_ENTIDADE_ATRELADA_A_CANAIS("erro.entidade.atrelada.a.canais"),
    ERRO_ENTIDADE_NAO_POSSIVEL_REMOVER("erro.entidade.nao.possivel.remover"),
    ERRO_CERTIFICADO_NAO_PERTENCE_A_PESSOA("erro.certificado.nao.pertence.a.pessoa"),

    ERRO_BLOQUEIO_JUDICIAL_DUPLICADO("erro.bloqueio.judicial.duplicado"),
    ERRO_BLOQUEIO_JUDICIAL_RESERVA_NULA("erro.bloqueio.judicial.reserva.nula"),
    ERRO_BLOQUEIO_JUDICIAL_RESERVA_NAO_ENCONTRADA("erro.bloqueio.judicial.rserva.nao.encontrada"),
    ERRO_BLOQUEIO_JUDICIAL_FUNDO_NULO("erro.bloqueio.judicial.fundo.nulo"),
    ERRO_BLOQUEIO_JUDICIAL_FUNDO_NAO_ENCONTRADO("erro.bloqueio.judicial.fundo.nao.encontrado"),
    ERRO_BLOQUEIO_JUDICIAL_CONTA_NULA("erro.bloqueio.judicial.conta.nula"),
    ERRO_BLOQUEIO_JUDICIAL_CONTA_NAO_ENCONTRADA("erro.bloqueio.judicial.conta.nao.encontrada"),
    ERRO_BLOQUEIO_JUDICIAL_PLANO_NULO("erro.bloqueio.judicial.plano.nulo"),
    ERRO_BLOQUEIO_JUDICIAL_PLANO_NAO_ENCONTRADO("erro.bloqueio.judicial.plano.nao.encontrado"),
    ERRO_BLOQUEIO_JUDICIAL_COBERTURA_NULA("erro.bloqueio.judicial.cobertura.nula"),
    ERRO_BLOQUEIO_JUDICIAL_COBERTURA_NAO_ENCONTRADA("erro.bloqueio.judicial.cobertura.nao.encontrada"),
    ERRO_BLOQUEIO_JUDICIAL_OPERACAO_NULA("erro.bloqueio.judicial.operacao.nula"),
    ERRO_BLOQUEIO_JUDICIAL_OPERACAO_NAO_ENCONTRADA("erro.bloqueio.judicial.operacao.nao.encontrada"),
    ERRO_BLOQUEIO_JUDICIAL_INICIO_VIGENCIA_NULA("erro.bloqueio.judicial.inicio.vigencia.nula"),
    ERRO_BLOQUEIO_JUDICIAL_FIM_VIGENCIA_ANTES_INICIO("erro.bloqueio.judicial.fim.vigencia.antes.inicio"),
    ERRO_BLOQUEIO_JUDICIAL_DATA_CALENDARIO_ANTES_INICIO_VIGENCIA(
            "erro.bloqueio.judicial.data.calendario.antes.inicio.vigencia"),
    ERRO_BLOQUEIO_JUDICIAL_DATA_CALENDARIO_ANTES_FIM_VIGENCIA("erro.bloqueio.judicial.data.calendario.antes.fim.vigencia"),
    ERRO_BLOQUEIO_JUDICIAL_NENHUM_CAMPO_VALOR_PREENCHIDO("erro.bloqueio.judicial.nenhum.campo.valor.preenchido"),
    ERRO_BLOQUEIO_JUDICIAL_PORCENTAGEM_FORA_DO_RANGE("erro.bloqueio.judicial.porcentagem.fora.do.range"),
    ERRO_BLOQUEIO_JUDICIAL_VALOR_MENOR_QUE_ZERO("erro.bloqueio.judicial.valor.menor.que.zero"),
    ERRO_BLOQUEIO_JUDICIAL_QTD_COTAS_MENOR_QUE_ZERO("erro.bloqueio.judicial.qtd.cotas.menor.que.zero"),
    ERRO_BLOQUEIO_JUDICIAL_MOTIVO_BLOQUEIO_OBRIGATORIO("erro.bloqueio.judicial.motivo.bloqueio.obrigatorio"),
    ERRO_BLOQUEIO_JUDICIAL_CERTIFICADO_SEM_SALDO("erro.bloqueio.judicial.certificado.sem.saldo"),

    ERRO_DEPOSITO_DATA_INFERIOR_INICIO_CERTIFICADO("erro.deposito.data.inferior.inicio.certificado"),
    ERRO_DEPOSITO_INFORMADO_COBRANCA_PORTABILIDADE("erro.deposito.informe.cobranca.portabilidade"),
    ERRO_DEPOSITO_PORTABILIDADE_INCORRETA("erro.deposito.portabilidade.incorreto"),
    ERRO_DEPOSITO_PORTABILIDADE_JA_ASSOCIADA("erro.deposito.portabilidade.ja.associada"),
    ERRO_DEPOSITO_PORTABILIDADE_INFORMADA_JA_RELACIONADA("erro.deposito.portabilidade.informada.ja.relacionado"),
    ERRO_DEPOSITO_VALOR_ZERADO("erro.deposito.valor.zerado"),
    ERRO_DEPOSITO_CAMPO_OBRIGATORIO_NAO_INFORMADO("erro.deposito.campo.obrigatorio.nao.informado"),
    ERRO_DEPOSITO_DESPESA_MAIOR_PAGO("erro.deposito.despesa.maior.pago"),
    ERRO_DEPOSITO_SEM_DATA_LIQUIDACAO("erro.deposito.sem.data.liquidacao"),
    ERRO_DEPOSITO_DATA_LIQUIDACAO_MENOR_DATA_ATUAL("erro.deposito.data.liquidacao.menor.data.atual"),
    ERRO_DEPOSITO_DATA_LIQUIDACAO_DIA_ATUAL("erro.deposito.data.liquidacao.dia.util"),
    ERRO_DEPOSITO_INFORME_DESCRICAO_DESPESAS_BANCARIAS("erro.deposito.informe.descricao.despesas.bancarias"),
    ERRO_DEPOSITO_VALOR_PAGAMENTO_ZERADO("erro.deposito.valor.pagamento.zerado"),
    ERRO_DEPOSITO_INFORME_MOTIVO_CANCELAMENTO("erro.deposito.informe.motivo.cancelamento"),

    ERRO_CONTROLE_DOCUMENTO_OBSERVACAO_NAO_INFORMADA("erro.controle.documento.observacao.nao.informada"),
    ERRO_CONTROLE_DOCUMENTO_OBSERVACAO_NAO_RELACIONADA_AO_DOCUMENTO(
            "erro.controle.documento.observacao.nao.relacionada.ao.documento"),
    ERRO_CONTROLE_DOCUMENTO_MOTIVO_OBSERVACAO_INVALIDO("erro.controle.documento.motivo.observacao.invalido"),
    ERRO_CONTROLE_DOCUMENTO_STATUS_INVALIDO("erro.controle.documento.status.invalido"),
    ERRO_CONTROLE_DOCUMENTO_STATUS_INVALIDO_ALTERACAO("erro.controle.documento.status.invalido.alteracao"),
    ERRO_CONTROLE_DOCUMENTO_DOCUMENTOS_NAO_ENCONTRADOS("erro.controle.documento.documentos.nao.encontrados"),
    ERRO_CONTROLE_DOCUMENTO_OPERACAO_INVALIDA("erro.controle.documento.operacao.invalida"),

    ERRO_SOLIC_PAGAMENTO_JUSTIFICATIVA_NULA("erro.solic.pagamento.justificativa.nula"),
    ERRO_SOLIC_PAGAMENTO_NAO_ENCONTRADA("erro.solic.pagamento.nao.encontrada"),
    ERRO_SOLIC_PAGAMENTO_NAO_PODE_ALTERAR("erro.solic.pagamento.nao.pode.alterar"),
    ERRO_SOLIC_PAGAMENTO_NAO_PODE_DAR_BAIXA_MANUAL("erro.solic.pagamento.nao.pode.dar.baixa.manual"),
    ERRO_SOLIC_PAGAMENTO_NAO_PODE_BLOQUEAR("erro.solic.pagamento.nao.pode.bloquear"),
    ERRO_SOLIC_PAGAMENTO_NAO_PODE_COLOCAR_EM_RECUPERACAO("erro.solic.pagamento.nao.pode.colocar.em.recuperacao"),
    ERRO_SOLIC_PAGAMENTO_NAO_PODE_RECUPERAR("erro.solic.pagamento.nao.pode.recuperar"),
    ERRO_SOLIC_PAGAMENTO_NAO_PODE_CANCELAR_RECUPERACAO("erro.solic.pagamento.nao.pode.cancelar.recuperacao"),
    ERRO_SOLIC_PAGAMENTO_NAO_PODE_CANCELAR_SOLICITACAO("erro.solic.pagamento.nao.pode.cancelar.solicitacao"),

    ERRO_SOLIC_PAGAMENTO_NOME_BANCO_NULO("erro.solic.pagamento.nome.banco.nulo"),
    ERRO_SOLIC_PAGAMENTO_COD_BANCO_NULO("erro.solic.pagamento.cod.banco.nulo"),
    ERRO_SOLIC_PAGAMENTO_CONTA_BANCARIA_NULA("erro.solic.pagamento.conta.bancaria.nula"),
    ERRO_SOLIC_PAGAMENTO_COD_AGENCIA_NULA("erro.solic.pagamento.cod.agencia.nula"),
    ERRO_SOLIC_PAGAMENTO_CONTA_FAVORECIDO_NAO_INFORMADA("erro.solic.pagamento.conta.favorecido.nao.informada"),
    ERRO_SOLIC_PAGAMENTO_COD_PESSOA_NAO_INFORMADO("erro.solic.pagamento.cod.pessoa.nao.informado"),
    ERRO_SOLIC_PAGAMENTO_CONTAS_NAO_ENCONTRADAS("erro.solic.pagamento.contas.nao.encontradas"),
    ERRO_SOLIC_PAGAMENTO_CONTA_NAO_ENCONTRADA("erro.solic.pagamento.conta.nao.encontrada"),
    ERRO_SOLIC_PAGAMENTO_NUM_MOVIMENTO_NULO("erro.solic.pagamento.num.movimento.nulo"),
    ERRO_SOLIC_PAGAMENTO_STATUS_NULO("erro.solic.pagamento.status.nulo"),
    ERRO_SOLIC_PAGAMENTO_STATUS_TITULO_NULO("erro.solic.pagamento.status.titulo.nulo"),
    ERRO_SOLIC_PAGAMENTO_NUM_TITULO_NULO("erro.solic.pagamento.num.titulo.nulo"),
    ERRO_SOLIC_PAGAMENTO_DESTINO_CHEQUE_OBRIGATORIO("erro.solic.pagamento.destino.cheque.obrigatorio"),

    ERRO_CANAL_PAGAMENTO_NAO_ENCONTRADA("erro.canal.pagamento.nao.encontrado"),

    ERRO_BATCH_NAO_EXISTE("erro.batch.nao.existe"),
    ERRO_BATCH_OPERACAO_NAO_INFORMADA("erro.batch.operacao.nao.informada"),
    ERRO_BATCH_OPERACAO_EM_EXECUCAO("erro.batch.operacao.em.execucao"),

    ERRO_DADO_ADICIONAL_SOMENTE_UM_FILTRO("erro.dado.adicional.somente.um.filtro"),
    ERRO_EXECUCAO_GRUPO_BATCH_NAO_ENCONTRADA("erro.execucao.grupo.batch.nao.encontrada"),
    ERRO_EXECUCAO_GRUPO_BATCH_TIPO_ALTERACAO_NAO_INFORMADO("erro.execucao.grupo.batch.tipo.alteracao.nao.informado"),
    ERRO_CONTA_PESSOA_NAO_ENCOTRADA("erro.conta.pessoa.nao.encotrada"),
    ERRO_CONTA_PESSOA_CONTA_NAO_ENCONTRADA("erro.conta.pessoa.conta.nao.encontrada"),
    ERRO_PESSOA_CODIGO_NAO_INFORMADO("erro.pessoa.codigo.nao.informado"),
    ERRO_COBERTURA_NAO_ENCONTRADA("erro.cobertura.nao.encontrada"),
    ERRO_COBERTURA_OPCAO_IR_NAO_DESABILITADA("erro.cobertura.opcao.ir.nao.desabilitada"),
    ERRO_COBERTURA_INCOMPATIVEL_COM_BENEFICIO("erro.cobertura.incompativel.com.beneficio"),
    ERRO_TIPO_PAGAMENTO_COBERTURA_NAO_ENCONTRADO("erro.tipo.pagamento.cobertura.nao.encontrado"),
    ERRO_TIPO_PAGAMENTO_COBERTURA_CAMPO_MAIORIDADE_VAZIO("erro.tipo.pagamento.cobertura.campo.maioridade.vazio"),
    ERRO_TIPO_PAGAMENTO_COBERTURA_PRAZO_MINIMO_MAXIMO_VAZIO("erro.tipo.pagamento.cobertura.prazo.minimo.maximo.vazio"),
    ERRO_ENTIDADE_UTILIZADA_EM_OPERACOES_JA_CADASTRADAS("erro.entidade.utilizada.em.operacoes.ja.cadastradas"),
    ERRO_VALIDACAO_QUANTIDADE_REGISTROS_INVALIDA("erro.validacao.quantidade.registros.invalida"),

    ERRO_PLANO_BENEF_WORKFLOW_ASSOCIADO("erro.plano.benef.workflow.associado"),
    ERRO_PLANO_BENEF_TIPO_PAGAMENTO_WORKFLOW_ASSOCIADO("erro.plano.benef.tipo.pagamento.workflow.associado"),
    ERRO_NAO_CLONAR_WORKFLOW("erro.nao.clonar.workflow"),
    ERRO_PLANO_NAO_ENCONTRADO("erro.plano.nao.encontrado"),
    ERRO_COBERTURA_PLANO_BENEFICIO_JA_EXISTENTE("erro.cobertura.plano.beneficio.ja.existente"),
    ERRO_DEVOLUCAO_ERRO_AO_EFETUAR_DEVOLUCAO_DE_REJEICAO("erro.devolucao.erro.ao.efetuar.devolucao.de.rejeicao"),
    ERRO_TIPO_PAGAMENTO_EXISTENTE("erro.tipo.pagamento.existente"),
    ERRO_TIPO_PAGAMENTO_NAO_ENCONTRADO("erro.tipo.pagamento.nao.encontrado"),

    ERRO_PORCENTAGEM_DEPENDENCIAS_NAO_INFORMADA("erro.porcentagem.dependencias.nao.informada"),
    ERRO_PRODUTO_NAO_ENCONTRADO("erro.produto.nao.encontrado"),
    ERRO_COBERTURA_PRODUTO_NAO_ENCONTRADO("erro.cobertura.produto.nao.encontrado"),
    ERRO_COBERTURA_DEPENDENCIA_PRODUTO_NAO_ENCONTRADO("erro.cobertura.dependencia.produto.nao.encontrado"),
    ERRO_NAO_DELETA_PRODUTO_COBERTURA_RELACIONADA("erro.nao.deleta.produto.cobertura.relacionada"),
    ERRO_COBERTURA_POSSUI_DEPENDENCIA("erro.cobertura.possui.dependencia"),
    ERRO_PRESTADOR_NAO_INFORMADO("erro.prestado.nao.informado"),
    ERRO_CAMPO_PRODUTO_OBRIGATORIO("erro.campo.produto.obrigatorio"),
    ERRO_PRODUTO_JA_EXISTENTE("erro.produto.ja.existente"),
    ERRO_PRODUTO_VIGENCIAS_NAO_INFORMADA("erro.produto.vigencias.nao.informada"),
    ERRO_CANAL_PRODUTO_DUPLICADO("erro.canal.produto.duplicado"),
    ERRO_CANAL_PRODUTO_NAO_ENCONTRADO("erro.canal.produto.nao.encontrado"),
    ERRO_COBERTURA_DATA_INTERVALO_INFORMADO("erro.cobertura.data.intervalo.informado"),

    ERRO_REGRA_NAO_ENCONTRADA("erro.regra.nao.encontrada"),
    ERRO_REGRA_JA_EXISTENTE("erro.regra.ja.existente"),

    ERRO_TIPO_EXIBICAO_INVALIDA("erro.tipo.exibicao.invalida"),
    ERRO_DATA_MOVIMENTACAO_OBRIGATORIO("erro.data.movimentacao.obrigatorio"),
    ERRO_PROPOSTA_NAO_POSSUI_PENDENCIA("erro.proposta.nao.possui.pendencia"),
    ERRO_INFORME_RENDIMENTO("erro.informe.rendimento"),

    ERRO_NAO_PERMITIDO_ALTERAR_DADOS("erro.nao.permitido.alterar.dados"),

    ERRO_TAMANHO_MAIOR_QUE_PERMITIDO("erro.tamanho.maior.que.permitido"),

    ERRO_SRO_EXTRACAO_TIPO_INCORRETO("erro.sro.extracao.tipo.incorreto");

    private String codigo;

    private CodigoValidacao(String codigo) {
        this.codigo = codigo;
    }

    @Override
    public String getCodigo() {
        return codigo;
    }

}
